import { Inter } from 'next/font/google'
import './globals.css'
import NavBar from './NavBar/page'



const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'كارم السياحية',  
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className} dir='rtl'>
       <NavBar />
          {children}
          </body>
        
    </html>
  )
}
